version: "3.9"
services:
  finance-manager-db:
    image: postgres
    environment:
      POSTGRES_USER: finance-manager
      POSTGRES_PASSWORD: finance-manager
      POSTGRES_DB: finance-manager
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: